### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by AminSajedian** [MSajedian/MSajedian.github.io#1]
- [x] Separate js and css from html files
- [x] Rename some files
- [x] add side bar

**Comment by MSajedian** [comment]
[ ] add progress bar
